### ISSUE TITLE
Cannot get the Example project to work on Windows 7 64 bit

### ISSUE THREAD

**Issue by dannyatkda** [Skycoder42/QtIFW-Advanced-Setup#2]
I have installed Python3.6.1 and "python" is in PATH.  I have also downloaded qpm.exe and is in PATH as well [downloaded today Jun 8, 2017].  And I also cloned this repository and I launch Qt 5.6.2 Qt Creator and tried to build Example.  That was OK.  However, I went to the command prompt (VS 2015 Developer CMD window) and typed:

```
C:\git\QtIFW-Advanced-Setup\Example>qpm install de.skycoder42.qtifw-advanced-setup
INFO: Package de.skycoder42.qtifw-advanced-setup has a different license (BSD_3_
CLAUSE) than it's dependant (NONE).
Installing de.skycoder42.qtifw-advanced-setup@1.0.0
QPM: 2017/06/08 16:30:26 ERROR: GetFileAttributesEx C:\git\QtIFW-Advanced-Setup\
Example\vendor\Skycoder42-QtIFW-Advanced-Setup-406f942\installer\translations\qp
m.json: The system cannot find the file specified.
```

So, I then I copied the qpm.json into the folder and I ran the command again and worked without error.

Now, what do I do?  I tried qmake Example.pro and then nmake but I get error:

```
C:\git\QtIFW-Advanced-Setup\Example>nmake

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" -
f Makefile.Release

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:WINDOWS "
/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' versio
n='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture
='*'" /MANIFEST:embed /OUT:release\Example.exe @C:\Users\danny\AppData\Local\Tem
p\nm64DF.tmp
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) publ
ic: __thiscall QString::~QString(void)" (__imp_??1QString@@QAE@XZ) referenced in
 function _main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) publ
ic: static class QString __cdecl QCoreApplication::translate(char const *,char c
onst *,char const *,int)" (__imp_?translate@QCoreApplication@@SA?AVQString@@PBD0
0H@Z) referenced in function _main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) publ
ic: __thiscall QApplication::QApplication(int &,char * *,int)" (__imp_??0QApplic
ation@@QAE@AAHPAPADH@Z) referenced in function _main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) publ
ic: virtual __thiscall QApplication::~QApplication(void)" (__imp_??1QApplication
@@UAE@XZ) referenced in function _main
main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) publ
ic: static enum QMessageBox::StandardButton __cdecl QMessageBox::information(cla
ss QWidget *,class QString const &,class QString const &,class QFlags<enum QMess
ageBox::StandardButton>,enum QMessageBox::StandardButton)" (__imp_?information@Q
MessageBox@@SA?AW4StandardButton@1@PAVQWidget@@ABVQString@@1V?$QFlags@W4Standard
Button@QMessageBox@@@@W421@@Z) referenced in function _main
MSVCRT.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol _WinMain
@16 referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_c
ommon_main_seh@@YAHXZ)
C:\Qt\Qt5.6.2\5.6\msvc2015_64\lib\qtmain.lib : warning LNK4272: library machine
type 'x64' conflicts with target machine type 'X86'
C:\Qt\Qt5.6.2\5.6\msvc2015_64\lib\Qt5Widgets.lib : warning LNK4272: library mach
ine type 'x64' conflicts with target machine type 'X86'
C:\Qt\Qt5.6.2\5.6\msvc2015_64\lib\Qt5Gui.lib : warning LNK4272: library machine
type 'x64' conflicts with target machine type 'X86'
C:\Qt\Qt5.6.2\5.6\msvc2015_64\lib\Qt5Core.lib : warning LNK4272: library machine
 type 'x64' conflicts with target machine type 'X86'
release\Example.exe : fatal error LNK1120: 6 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\link.EXE"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

C:\git\QtIFW-Advanced-Setup\Example>
```

When I try to build "nmake installer":

```
C:\git\QtIFW-Advanced-Setup\Example>nmake installer

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        python C:\git\QtIFW-Advanced-Setup\deploy\deploy.py win_release C:/Qt/Qt
5.6.2/5.6/msvc2015_64/bin C:/Qt/Qt5.6.2/5.6/msvc2015_64/plugins C:/Qt/Qt5.6.2/5.
6/msvc2015_64/translations C:/git/QtIFW-Advanced-Setup/Example/release/Example.e
xe C:/git/QtIFW-Advanced-Setup/Example/deployed C:/git/QtIFW-Advanced-Setup/Exam
ple/Example.pro
C:/git/QtIFW-Advanced-Setup/Example/release/Example.exe C:/git/QtIFW-Advanced-Se
tup/Example/deployed\Example.exe
Traceback (most recent call last):
  File "C:\git\QtIFW-Advanced-Setup\deploy\deploy.py", line 134, in <module>
    copyany(depsrc, binname)
  File "C:\git\QtIFW-Advanced-Setup\deploy\deploy.py", line 29, in copyany
    shutil.copytree(src, dst)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\shutil.py", li
ne 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/g
it/QtIFW-Advanced-Setup/Example/release/Example.exe'
NMAKE : fatal error U1077: 'C:\Users\danny\AppData\Local\Programs\Python\Python3
6\python.EXE' : return code '0x1'
Stop.

C:\git\QtIFW-Advanced-Setup\Example>
```

[I also have the latest QtIFW installed V2.0.5-1]

I have VS2015 installed and Qt 5.6.2.  What else am I missing?

**Comment by Skycoder42** [comment]
Regarding the qpm problem, see #1 and Cutehacks/qpm#41. It's an error of qpm.

Regarding the compilation errors: The interesting part here is:
```
C:\Qt\Qt5.6.2\5.6\msvc2015_64\lib\Qt5Core.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'
```
It looks like you are trying to compile with Qt for msvc x64 on an x86 machine? Try to compile one of the Qt example projects.

The fact that `nmake installer` fails is simply because `nmake` failed - The executable does not exist. Furthermore, you would need to run `nmake deploy` first as well, because the binaries need to be deployed first (this will fail as well, unless `nmake` succeeds), as the Example was configured that way. You can simply run `nmake install` as shortcut for the example.

**Comment by dannyatkda** [comment]
OK, it was my mistake on the qmake/nmake part (somehow Example.pro got messed up on the process so I had to revert it).  I got nmake to build OK:

```
C:\git\QtIFW-Advanced-Setup\Example>nmake

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.
exe" -f Makefile.Release

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -O2 -MD
-GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -D
UNICODE -DWIN32 -DWIN64 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LI
B -DNDEBUG -I. -I..\..\..\Qt\Qt5.6.2\5.6\msvc2015_64\include -I..\..\..\Qt\Qt5.6
.2\5.6\msvc2015_64\include\QtWidgets -I..\..\..\Qt\Qt5.6.2\5.6\msvc2015_64\inclu
de\QtGui -I..\..\..\Qt\Qt5.6.2\5.6\msvc2015_64\include\QtANGLE -I..\..\..\Qt\Qt5
.6.2\5.6\msvc2015_64\include\QtCore -Irelease -I..\..\..\Qt\Qt5.6.2\5.6\msvc2015
_64\mkspecs\win32-msvc2015 -Forelease\ @C:\Users\danny\AppData\Local\Temp\nm2AD2
.tmp
main.cpp
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:WINDOWS "
/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' versio
n='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture
='*'" /MANIFEST:embed /OUT:release\Example.exe @C:\Users\danny\AppData\Local\Tem
p\nm2DA0.tmp
```
However, when I tried nmake install:

```
C:\git\QtIFW-Advanced-Setup\Example>nmake install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.
exe" -f Makefile.Release install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        python C:\git\QtIFW-Advanced-Setup\deploy\deploy.py win_release C:/Qt/Qt
5.6.2/5.6/msvc2015_64/bin C:/Qt/Qt5.6.2/5.6/msvc2015_64/plugins C:/Qt/Qt5.6.2/5.
6/msvc2015_64/translations C:/git/QtIFW-Advanced-Setup/Example/release/Example.e
xe C:/git/QtIFW-Advanced-Setup/Example/deployed C:/git/QtIFW-Advanced-Setup/Exam
ple/Example.pro
C:/git/QtIFW-Advanced-Setup/Example/release/Example.exe C:/git/QtIFW-Advanced-Se
tup/Example/deployed\Example.exe
C:\git\QtIFW-Advanced-Setup\Example\deployed\Example.exe 64 bit, release executa
ble
Adding Qt5Svg for qsvgicon.dll
Direct dependencies: Qt5Core Qt5Widgets
All dependencies   : Qt5Core Qt5Gui Qt5Widgets
To be deployed     : Qt5Core Qt5Gui Qt5Svg Qt5Widgets
Updating Qt5Core.dll.
Updating Qt5Gui.dll.
Updating Qt5Svg.dll.
Updating Qt5Widgets.dll.
Updating libGLESV2.dll.
Updating libEGL.dll.
Updating d3dcompiler_47.dll.
Updating opengl32sw.dll.
Updating vcredist_x64.exe.
Patching Qt5Core.dll...
Creating directory C:/git/QtIFW-Advanced-Setup/Example/deployed/iconengines.
Updating qsvgicon.dll.
Creating directory C:/git/QtIFW-Advanced-Setup/Example/deployed/imageformats.
Updating qdds.dll.
Updating qgif.dll.
Updating qicns.dll.
Updating qico.dll.
Updating qjpeg.dll.
Updating qsvg.dll.
Updating qtga.dll.
Updating qtiff.dll.
Updating qwbmp.dll.
Updating qwebp.dll.
Creating directory C:/git/QtIFW-Advanced-Setup/Example/deployed/platforms.
Updating qwindows.dll.
Could Not Find C:\git\QtIFW-Advanced-Setup\Example\deployed\vcredist_x86.exe
Updating 'C:/git/QtIFW-Advanced-Setup/Example/example_de.qm'...
    Generated 2 translation(s) (2 finished and 0 unfinished)
Traceback (most recent call last):
  File "C:\git\QtIFW-Advanced-Setup\deploy\deploy.py", line 139, in <module>
    cp_translations()
  File "C:\git\QtIFW-Advanced-Setup\deploy\deploy.py", line 115, in cp_translati
ons
    shutil.copy2(ofile, dfile)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\shutil.py", li
ne 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\shutil.py", li
ne 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'C:/git/QtIFW-Advanced-Setup/Example\\deployed\\translatio
ns\\example_de.qm' and 'C:/git/QtIFW-Advanced-Setup/Example/deployed\\translatio
ns\\example_de.qm' are the same file
NMAKE : fatal error U1077: 'C:\Users\danny\AppData\Local\Programs\Python\Python3
6\python.EXE' : return code '0x1'
Stop.
```

What should I try next? Thanks. Danny

**Comment by dannyatkda** [comment]
I also noticed that vcredist isn't being found: it shows the error message whether I have QT_INSTALL_BINS defined or not.  And when I build for 32 bit, it complains about vcredist_x64.exe while for 64 bit, it complains about vcredist_x86.exe....

**Comment by Skycoder42** [comment]
The fact that he complains about not finding the x86/x64 redists is fine. It's a part of the script thats not clean yet. It's because I always delete both of them, just to be safe (See https://github.com/Skycoder42/QtIFW-Advanced-Setup/blob/master/deploy/deploy.py#L58). And this of course fails for the one not existing. (The delete is required, as the vc_redist are part of the installer, not the deployment).

Regarding the copy fail: That is indeed a bug, that only happens if you build inside of the source directory. Try to run it shadowed, for example, if you are inside of the Example directory:
```
mkdir ..\example-build
cd ..\example-build
qmake ..\Example

nmake
```

If you build it from an IDE, this is done automatically.

**Comment by dannyatkda** [comment]
Well, now I'm getting a different error.

1. I renamed my previous directory.
2. I re- cloned from github
3. I ran qpm in Example directory.
4. Copied the json file to the missing directory
5. re-ran qpm and works OK.
6. mkdir ..\ebuild
7. cd ..\ebuild
8. (32 bit qt in the PATH along with x86 VS 2015 native CMD prompt): qmake ..\Example\Example.pro
9. nmake [worked OK]
10. nmake install

I get filenotfound error:

```
C:\git\QtIFW-Advanced-Setup\ebuild>nmake install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" -
f Makefile.Release install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        python C:\git\QtIFW-Advanced-Setup\deploy\deploy.py win_release C:/Qt/Qt
5.6.2x32/5.6/msvc2015/bin C:/Qt/Qt5.6.2x32/5.6/msvc2015/plugins C:/Qt/Qt5.6.2x32
/5.6/msvc2015/translations C:/git/QtIFW-Advanced-Setup/ebuild/release/Example.ex
e C:/git/QtIFW-Advanced-Setup/ebuild/deployed C:/git/QtIFW-Advanced-Setup/Exampl
e/Example.pro
C:/git/QtIFW-Advanced-Setup/ebuild/release/Example.exe C:/git/QtIFW-Advanced-Set
up/ebuild/deployed\Example.exe
C:\git\QtIFW-Advanced-Setup\ebuild\deployed\Example.exe 32 bit, release executab
le
Adding Qt5Svg for qsvgicon.dll
Direct dependencies: Qt5Core Qt5Widgets
All dependencies   : Qt5Core Qt5Gui Qt5Widgets
To be deployed     : Qt5Core Qt5Gui Qt5Svg Qt5Widgets
Updating Qt5Core.dll.
Updating Qt5Gui.dll.
Updating Qt5Svg.dll.
Updating Qt5Widgets.dll.
Updating libGLESV2.dll.
Updating libEGL.dll.
Updating d3dcompiler_47.dll.
Updating opengl32sw.dll.
Updating vcredist_x86.exe.
Patching Qt5Core.dll...
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/iconengines.
Updating qsvgicon.dll.
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/imageformats.
Updating qdds.dll.
Updating qgif.dll.
Updating qicns.dll.
Updating qico.dll.
Updating qjpeg.dll.
Updating qsvg.dll.
Updating qtga.dll.
Updating qtiff.dll.
Updating qwbmp.dll.
Updating qwebp.dll.
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/platforms.
Updating qwindows.dll.
Could Not Find C:\git\QtIFW-Advanced-Setup\ebuild\deployed\vcredist_x64.exe
Updating 'C:/git/QtIFW-Advanced-Setup/Example/example_de.qm'...
    Generated 2 translation(s) (2 finished and 0 unfinished)
        python C:\git\QtIFW-Advanced-Setup\installer\build.py C:\git\QtIFW-Advan
ced-Setup\Example qtifw-installer C:\Qt\Qt5.6.2x32\5.6\msvc2015\bin\..\..\..\Too
ls\QtInstallerFramework\2.0\bin\ "Example Installer.exe" offline x86 config.xml
C:\git\QtIFW-Advanced-Setup\installer\config\controller.js p de.skycoder42.qtifw
sample m meta d data d C:\git\QtIFW-Advanced-Setup\ebuild\deployed f ..\LICENSE
p de.skycoder42.advancedsetup m C:\git\QtIFW-Advanced-Setup\installer\packages\d
e.skycoder42.advancedsetup\meta d C:\git\QtIFW-Advanced-Setup\installer\packages
\de.skycoder42.advancedsetup\data p com.microsoft.vcredist.x86 m C:\git\QtIFW-Ad
vanced-Setup\installer\packages\com.microsoft.vcredist\meta f "C:\Program Files
(x86)\Microsoft Visual Studio 14.0\VC\\redist\1033\vcredist_x86.exe"
Traceback (most recent call last):
  File "C:\git\QtIFW-Advanced-Setup\installer\build.py", line 154, in <module>
    create_offline()
  File "C:\git\QtIFW-Advanced-Setup\installer\build.py", line 124, in create_off
line
    os.path.join(outdir, target)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\subprocess.py"
, line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\subprocess.py"
, line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\subprocess.py"
, line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
NMAKE : fatal error U1077: 'C:\Users\danny\AppData\Local\Programs\Python\Python3
6\python.EXE' : return code '0x1'
Stop.
```
And when I run nmake installer [thinking I should have tried installer first instead of install] I get another error: PermissionError

```
C:\git\QtIFW-Advanced-Setup\ebuild>nmake installer

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        python C:\git\QtIFW-Advanced-Setup\deploy\deploy.py win_release C:/Qt/Qt
5.6.2x32/5.6/msvc2015/bin C:/Qt/Qt5.6.2x32/5.6/msvc2015/plugins C:/Qt/Qt5.6.2x32
/5.6/msvc2015/translations C:/git/QtIFW-Advanced-Setup/ebuild/release/Example.ex
e C:/git/QtIFW-Advanced-Setup/ebuild/deployed C:/git/QtIFW-Advanced-Setup/Exampl
e/Example.pro
C:/git/QtIFW-Advanced-Setup/ebuild/release/Example.exe C:/git/QtIFW-Advanced-Set
up/ebuild/deployed\Example.exe
C:\git\QtIFW-Advanced-Setup\ebuild\deployed\Example.exe 32 bit, release executab
le
Adding Qt5Svg for qsvgicon.dll
Direct dependencies: Qt5Core Qt5Widgets
All dependencies   : Qt5Core Qt5Gui Qt5Widgets
To be deployed     : Qt5Core Qt5Gui Qt5Svg Qt5Widgets
Updating Qt5Core.dll.
Updating Qt5Gui.dll.
Updating Qt5Svg.dll.
Updating Qt5Widgets.dll.
Updating libGLESV2.dll.
Updating libEGL.dll.
Updating d3dcompiler_47.dll.
Updating opengl32sw.dll.
Updating vcredist_x86.exe.
Patching Qt5Core.dll...
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/iconengines.
Updating qsvgicon.dll.
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/imageformats.
Updating qdds.dll.
Updating qgif.dll.
Updating qicns.dll.
Updating qico.dll.
Updating qjpeg.dll.
Updating qsvg.dll.
Updating qtga.dll.
Updating qtiff.dll.
Updating qwbmp.dll.
Updating qwebp.dll.
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/platforms.
Updating qwindows.dll.
Could Not Find C:\git\QtIFW-Advanced-Setup\ebuild\deployed\vcredist_x64.exe
Updating 'C:/git/QtIFW-Advanced-Setup/Example/example_de.qm'...
    Generated 2 translation(s) (2 finished and 0 unfinished)
        python C:\git\QtIFW-Advanced-Setup\installer\build.py C:\git\QtIFW-Advan
ced-Setup\Example qtifw-installer C:\Qt\Qt5.6.2x32\5.6\msvc2015\bin\..\..\..\Too
ls\QtInstallerFramework\2.0\bin\ "Example Installer.exe" offline x86 config.xml
C:\git\QtIFW-Advanced-Setup\installer\config\controller.js p de.skycoder42.qtifw
sample m meta d data d C:\git\QtIFW-Advanced-Setup\ebuild\deployed f ..\LICENSE
p de.skycoder42.advancedsetup m C:\git\QtIFW-Advanced-Setup\installer\packages\d
e.skycoder42.advancedsetup\meta d C:\git\QtIFW-Advanced-Setup\installer\packages
\de.skycoder42.advancedsetup\data p com.microsoft.vcredist.x86 m C:\git\QtIFW-Ad
vanced-Setup\installer\packages\com.microsoft.vcredist\meta f "C:\Program Files
(x86)\Microsoft Visual Studio 14.0\VC\\redist\1033\vcredist_x86.exe"
Traceback (most recent call last):
  File "C:\git\QtIFW-Advanced-Setup\installer\build.py", line 149, in <module>
    create_install_dir(7)
  File "C:\git\QtIFW-Advanced-Setup\installer\build.py", line 75, in create_inst
all_dir
    copy_pkg(pkg, state, arg, "data", False)
  File "C:\git\QtIFW-Advanced-Setup\installer\build.py", line 42, in copy_pkg
    shutil.copy2(pkgsrc, resName)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\shutil.py", li
ne 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\shutil.py", li
ne 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'qtifw-installer\\packages\\com.m
icrosoft.vcredist.x86\\data\\vcredist_x86.exe'
NMAKE : fatal error U1077: 'C:\Users\danny\AppData\Local\Programs\Python\Python3
6\python.EXE' : return code '0x1'
Stop.
```

Am I missing some environment variables?

**Comment by Skycoder42** [comment]
For the first error, set the `QTIFW_BIN` variable (See https://github.com/Skycoder42/QtIFW-Advanced-Setup/blob/master/README.md#variable-documentation)

Regading the installer vs install:
To create an installer, an application needs to be deployed first. This package supports this by providing the 2 make targets `make deploy` and `make installer`. To make it easier, I created the `make install` target as well. It's simply a shortcut for those two. I case of the example, a deployment must be done before creating the installer, thus `make install`. But of course, you can run the two targets by hand as well.

And for the last problem (sorry for giving you so much):
It seems that for whatever reason, Windows does not allow me do delete a file I copied myself -_- You have to delete this file by hand via the explorer, until I am able to find out why.... Note: This should only happen the second time you run install or installer. i.e. a "clean build" should work.

**Comment by dannyatkda** [comment]
I've made a bat file to do the steps.  [qtrun - Copy.txt](https://github.com/Skycoder42/QtIFW-Advanced-Setup/files/1065385/qtrun.-.Copy.txt) [download and rename the extension to .bat]

[And yes, I started with a fresh clone.]

And everything but the last nmake install seems to work OK.

Here's the last bit:
```
C:\git\QtIFW-Advanced-Setup\ebuild>nmake installer

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        python C:\git\QtIFW-Advanced-Setup\deploy\deploy.py win_release C:/Qt/Qt
5.6.2x32/5.6/msvc2015/bin C:/Qt/Qt5.6.2x32/5.6/msvc2015/plugins C:/Qt/Qt5.6.2x32
/5.6/msvc2015/translations C:/git/QtIFW-Advanced-Setup/ebuild/release/Example.ex
e C:/git/QtIFW-Advanced-Setup/ebuild/deployed C:/git/QtIFW-Advanced-Setup/Exampl
e/Example.pro
C:/git/QtIFW-Advanced-Setup/ebuild/release/Example.exe C:/git/QtIFW-Advanced-Set
up/ebuild/deployed\Example.exe
C:\git\QtIFW-Advanced-Setup\ebuild\deployed\Example.exe 32 bit, release executab
le
Adding Qt5Svg for qsvgicon.dll
Direct dependencies: Qt5Core Qt5Widgets
All dependencies   : Qt5Core Qt5Gui Qt5Widgets
To be deployed     : Qt5Core Qt5Gui Qt5Svg Qt5Widgets
Updating Qt5Core.dll.
Updating Qt5Gui.dll.
Updating Qt5Svg.dll.
Updating Qt5Widgets.dll.
Updating libGLESV2.dll.
Updating libEGL.dll.
Updating d3dcompiler_47.dll.
Updating opengl32sw.dll.
Updating vcredist_x86.exe.
Patching Qt5Core.dll...
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/iconengines.
Updating qsvgicon.dll.
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/imageformats.
Updating qdds.dll.
Updating qgif.dll.
Updating qicns.dll.
Updating qico.dll.
Updating qjpeg.dll.
Updating qsvg.dll.
Updating qtga.dll.
Updating qtiff.dll.
Updating qwbmp.dll.
Updating qwebp.dll.
Creating directory C:/git/QtIFW-Advanced-Setup/ebuild/deployed/platforms.
Updating qwindows.dll.
Could Not Find C:\git\QtIFW-Advanced-Setup\ebuild\deployed\vcredist_x64.exe
Updating 'C:/git/QtIFW-Advanced-Setup/Example/example_de.qm'...
    Generated 2 translation(s) (2 finished and 0 unfinished)
        python C:\git\QtIFW-Advanced-Setup\installer\build.py C:\git\QtIFW-Advan
ced-Setup\Example qtifw-installer C:\Qt\Qt5.6.2x32\5.6\msvc2015\bin\..\..\..\Too
ls\QtInstallerFramework\2.0\bin\ "Example Installer.exe" offline x86 config.xml
C:\git\QtIFW-Advanced-Setup\installer\config\controller.js p de.skycoder42.qtifw
sample m meta d data d C:\git\QtIFW-Advanced-Setup\ebuild\deployed f ..\LICENSE
p de.skycoder42.advancedsetup m C:\git\QtIFW-Advanced-Setup\installer\packages\d
e.skycoder42.advancedsetup\meta d C:\git\QtIFW-Advanced-Setup\installer\packages
\de.skycoder42.advancedsetup\data p com.microsoft.vcredist.x86 m C:\git\QtIFW-Ad
vanced-Setup\installer\packages\com.microsoft.vcredist\meta f "C:\Program Files
(x86)\Microsoft Visual Studio 14.0\VC\\redist\1033\vcredist_x86.exe"
Traceback (most recent call last):
  File "C:\git\QtIFW-Advanced-Setup\installer\build.py", line 154, in <module>
    create_offline()
  File "C:\git\QtIFW-Advanced-Setup\installer\build.py", line 124, in create_off
line
    os.path.join(outdir, target)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\subprocess.py"
, line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\subprocess.py"
, line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\danny\AppData\Local\Programs\Python\Python36\lib\subprocess.py"
, line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
NMAKE : fatal error U1077: 'C:\Users\danny\AppData\Local\Programs\Python\Python3
6\python.EXE' : return code '0x1'
Stop.


```

**Comment by Skycoder42** [comment]
Ah, you misunderstood the variables. They are **not** environment variables, but qmake variables. `QTIFW_BIN` must be set inside the pro file, or via a qmake config:

```
REM before running qmake, update QTIFW_BIN
echo QTIFW_BIN=C:\Qt\QtIFW2.0.5\bin >> ..\Example\.qmake.conf
qmake ..\Example\Example.pro
```

In your own project, you would set this one in the pro file. But using a `.qmake.conf` file should be fine as well.

**Comment by dannyatkda** [comment]
Success!
[qtrun ver2.txt](https://github.com/Skycoder42/QtIFW-Advanced-Setup/files/1065418/qtrun.ver2.txt)

I've even ran the installer to see that it worked correctly on installing 32 bit where nothing is installed and worked like a charm.  Thanks for your time and for this project....

**Comment by Skycoder42** [comment]
Wonderful, thanks for your patience. I will keep this issue open, as a guide for others, until I was able to fix the problems

**Comment by Skycoder42** [comment]
Regarding the qpm problem:

The error has already been fixed in qpm master, but has not been released yet. Until 0.11.0 has been released, you can download the binary from here:

https://storage.googleapis.com/www.qpm.io/download/latest/windows_amd64/qpm.exe
https://storage.googleapis.com/www.qpm.io/download/latest/windows_386/qpm.exe

(yes, I wanted to keep this open... )

**Comment by 0xlitf** [comment]
I build the qpm by myself, it works.
go get qpm.io/qpm
go build qpm.io/qpm

evn: go 1.8.1 Windows 10

**Comment by Skycoder42** [comment]
@4u1kto Yes, this is possible, but requires go. As such, the download is easier for most users.

I'm closing this now as the bugs have been fixed and the readme updated with all neccessary hints.
